# Start the service with the command 'docker-compose up -d'

version: '3.9'

services:
  mongo-ipfs-service:
    image: mongo:4.2.0
    container_name: mongo-p2wdb-upload
    ports:
      - '5555:27017' # <host port>:<container port>
    volumes:
      - ../data/database:/data/db
    command: mongod --logpath=/dev/null # -- quiet
    restart: always

  ipfs-service:
    build: .
    #image: christroutner/ipfs-service-provider:v5.0.1
    container_name: ipfs-service
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 1000mb
    links:
      - mongo-ipfs-service
    ports:
      - '5010:5010' # <host port>:<container port>
      - '4001:4001' # IPFS TCP
      - '4003:4003' # IPFS WS
    volumes:
      - ../data/ipfsdata:/home/safeuser/p2wdb-image-upload-backend/.ipfsdata
      - ./start-production.sh:/home/safeuser/p2wdb-image-upload-backend/start-production.sh
    restart: always
